export { DiscordClientError, DiscordError, DiscordServerError } from './base.js';
export {
  BotScopeUnresolvedError,
  CancelledError,
  DiscordAuthError,
  DiscordCloudflareBlocked,
  DiscordNotFoundError,
  DiscordPermissionError,
  DiscordRateLimitError,
  DmConsentRejected,
  DmConsentRequired,
  DmOutcomeUnknown,
  DryRunPreview,
  GuildNotAllowedError,
  GuildScopeUnresolvedError,
  PayloadConfirmationApprovalExpired,
  PayloadConfirmationApprovalMismatch,
  PayloadConfirmationApprovalMissing,
  PayloadConfirmationApprovalReplayed,
  PayloadConfirmationMismatch,
  PayloadConfirmationRequired,
  RuntimeAccessDeniedError,
  RuntimeAccessUnknownError,
  ScopeRejectedError,
  ValidationError,
  type ValidationIssue,
} from './client.js';
export {
  BulkheadFullError,
  CircuitOpenError,
  DiscordServerErrorImpl,
  ExternalServiceError,
  InternalError,
} from './server.js';
